#!/bin/sh
### BEGIN INIT INFO
# Provides:          dropbear
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lightweight SSH server
# Description:       Dropbear SSH init script
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dropbear
NAME=dropbear
DESC="Dropbear SSH server"
PIDFILE=/var/run/$NAME.pid
DEFAULTCFG=/etc/default/dropbear

# Default settings
DROPBEAR_PORT=22
DROPBEAR_EXTRA_ARGS=""
NO_START=0
DROPBEAR_RECEIVE_WINDOW="65536"

# Source configuration file if it exists
[ -f "$DEFAULTCFG" ] && . "$DEFAULTCFG"

. /lib/lsb/init-functions

case "$1" in
  start)
    [ "$NO_START" = "0" ] || {
      log_warning_msg "$DESC is disabled in $DEFAULTCFG"
      exit 0
    }

    log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
      --exec $DAEMON -- -p "$DROPBEAR_PORT" -W "$DROPBEAR_RECEIVE_WINDOW" $DROPBEAR_EXTRA_ARGS
    log_end_msg $?
    ;;
    
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    log_end_msg $?
    ;;
    
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
    
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
