#!/usr/bin/python3
# -*- coding: utf-8 -*-

import socket
import threading
import select
import sys
import time
import getopt

# Konfigurasi Default
LISTENING_ADDR = '127.0.0.1'
LISTENING_PORT = 700  # <-- DIKEMBALIKAN KE PORT ASLI
PASS = ''

# Konstanta
BUFLEN = 4096 * 4
TIMEOUT = 60
DEFAULT_HOST = '127.0.0.1:69'
# PY3FIX: Response diubah menjadi bytes
RESPONSE = b'HTTP/1.1 101 Switching Protocol\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: foo\r\n\r\n'


class Server(threading.Thread):
    def __init__(self, host, port):
        threading.Thread.__init__(self)
        self.running = False
        self.host = host
        self.port = port
        self.threads = []
        self.threadsLock = threading.Lock()
        self.logLock = threading.Lock()

    def run(self):
        self.soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.soc.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.soc.settimeout(2)
        self.soc.bind((self.host, self.port))
        self.soc.listen(0)
        self.running = True

        try:
            while self.running:
                try:
                    c, addr = self.soc.accept()
                    c.setblocking(True)
                except socket.timeout:
                    continue

                conn = ConnectionHandler(c, self, addr)
                conn.start()
                self.addConn(conn)
        finally:
            self.running = False
            self.soc.close()

    def printLog(self, log):
        with self.logLock:
            # PY3FIX: Menggunakan print() sebagai fungsi
            print(log)

    def addConn(self, conn):
        with self.threadsLock:
            if self.running:
                self.threads.append(conn)

    def removeConn(self, conn):
        with self.threadsLock:
            if conn in self.threads:
                self.threads.remove(conn)

    def close(self):
        self.running = False
        with self.threadsLock:
            threads = list(self.threads)
            for c in threads:
                c.close()


class ConnectionHandler(threading.Thread):
    def __init__(self, socClient, server, addr):
        threading.Thread.__init__(self)
        self.clientClosed = False
        self.targetClosed = True
        self.client = socClient
        self.client_buffer = b'' # PY3FIX: Buffer adalah bytes
        self.server = server
        self.log = f'Connection: {addr}'

    def close(self):
        try:
            if not self.clientClosed:
                self.client.shutdown(socket.SHUT_RDWR)
                self.client.close()
        except OSError:
            pass
        finally:
            self.clientClosed = True

        try:
            if not self.targetClosed:
                self.target.shutdown(socket.SHUT_RDWR)
                self.target.close()
        except OSError:
            pass
        finally:
            self.targetClosed = True

    def run(self):
        try:
            self.client_buffer = self.client.recv(BUFLEN)

            # PY3FIX: Decode buffer untuk memprosesnya sebagai teks
            header_text = self.client_buffer.decode('utf-8', errors='ignore')

            hostPort = self.findHeader(header_text, 'X-Real-Host')

            if hostPort == '':
                hostPort = DEFAULT_HOST

            split = self.findHeader(header_text, 'X-Split')
            if split != '':
                self.client.recv(BUFLEN)

            if hostPort:
                passwd = self.findHeader(header_text, 'X-Pass')
                
                allow_connect = False
                if len(PASS) == 0:
                    allow_connect = True
                elif passwd == PASS:
                    allow_connect = True
                
                if allow_connect:
                    self.method_CONNECT(hostPort)
                else:
                    # PY3FIX: Encode pesan error ke bytes
                    self.client.send(b'HTTP/1.1 401 Unauthorized\r\n\r\n')

            else:
                self.server.printLog('- No X-Real-Host header found')
                self.client.send(b'HTTP/1.1 400 Bad Request\r\n\r\n')

        except Exception as e:
            # PY3FIX: Menggunakan str(e) untuk mendapatkan pesan error
            self.log += f' - error: {str(e)}'
            self.server.printLog(self.log)
        finally:
            self.close()
            self.server.removeConn(self)

    def findHeader(self, head, header):
        try:
            aux = head.lower().find(header.lower() + ': ')
            if aux == -1:
                return ''
            
            aux = head.find(':', aux)
            head = head[aux + 2:]
            aux = head.find('\r\n')

            if aux == -1:
                return ''
            
            return head[:aux].strip()
        except Exception:
            return ''

    def connect_target(self, host):
        i = host.find(":")
        if i != -1:
            port = int(host[i+1:])
            host = host[:i]
        else:
            port = 443 # Port default untuk CONNECT (HTTPS)

        (soc_family, _, _, _, address) = socket.getaddrinfo(host, port)[0]

        self.target = socket.socket(soc_family)
        self.targetClosed = False
        self.target.connect(address)

    def method_CONNECT(self, path):
        self.log += f' - CONNECT {path}'
        self.connect_target(path)
        self.client.sendall(RESPONSE)
        self.client_buffer = b''
        self.server.printLog(self.log)
        self.doCONNECT()

    def doCONNECT(self):
        socs = [self.client, self.target]
        count = 0
        error = False
        while not error:
            count += 1
            (recv, _, err) = select.select(socs, [], socs, 3)
            
            if err:
                error = True
            
            if recv:
                for in_ in recv:
                    try:
                        # Data yang diterima sudah dalam bentuk bytes, bisa langsung dikirim
                        data = in_.recv(BUFLEN)
                        if data:
                            if in_ is self.client:
                                self.target.send(data)
                            else:
                                self.client.send(data)
                            count = 0
                        else:
                            # Socket ditutup
                            error = True
                            break
                    except OSError:
                        error = True
                        break
            
            if count > TIMEOUT / 3:
                error = True


def print_usage():
    # PY3FIX: Menggunakan print() sebagai fungsi
    print("Usage: proxy.py [options]")
    print("Options:")
    print("  -p, --port <port>      Listen on this port")
    print("  -b, --bind <address>   Bind to this address")
    print("  -h, --help             Show this help message")
    print("\nExample: sudo ./proxy.py -b 0.0.0.0 -p 80")

def parse_args(argv):
    global LISTENING_ADDR
    global LISTENING_PORT
    
    # PY3FIX: Logika argumen port dari baris perintah diperbaiki
    original_port = LISTENING_PORT

    try:
        opts, _ = getopt.getopt(argv, "hb:p:", ["bind=", "port="])
    except getopt.GetoptError:
        print_usage()
        sys.exit(2)
        
    for opt, arg in opts:
        if opt == '-h':
            print_usage()
            sys.exit()
        elif opt in ("-b", "--bind"):
            LISTENING_ADDR = arg
        elif opt in ("-p", "--port"):
            try:
                LISTENING_PORT = int(arg)
            except ValueError:
                print("Error: Port must be a number.")
                sys.exit(2)
    
    # Handle kasus di mana skrip dipanggil tanpa argumen port
    # Ini untuk mengatasi variabel LISTENING_PORT dari kode asli
    if len(sys.argv) > 1 and '-p' not in sys.argv and '--port' not in sys.argv:
        try:
            LISTENING_PORT = int(sys.argv[1])
        except (ValueError, IndexError):
            LISTENING_PORT = original_port


def main():
    parse_args(sys.argv[1:])
    
    # PY3FIX: Menggunakan print() sebagai fungsi
    print("\n:------- Python 3 Proxy -------:")
    print(f"  Listening on: {LISTENING_ADDR}:{LISTENING_PORT}")
    print("--------------------------------\n")
    
    server = Server(LISTENING_ADDR, LISTENING_PORT)
    server.start()
    
    try:
        while True:
            time.sleep(2)
    except KeyboardInterrupt:
        print('\nStopping proxy server...')
        server.close()
        print('Server stopped.')

if __name__ == '__main__':
    main()
